### PR TITLE
chore: update sierra file stem

### PR DESCRIPTION
**Pull request by tserg**
Update `.sierra` to `.contract_class` as per https://github.com/software-mansion/scarb/pull/610

### CODE REVIEW

**Comment by smonicas** [comment]
Hi thanks for your PR. If i understand correctly this will be from the next scarb version however i believe we should maintain backward compatibility with older scarb versions. I think checking if it ends with `.sierra` or `.contract_class` should work just fine. What do you think?

**Comment by tserg** [comment]
> Hi thanks for your PR. If i understand correctly this will be from the next scarb version however i believe we should maintain backward compatibility with older scarb versions. I think checking if it ends with `.sierra` or `.contract_class` should work just fine. What do you think?

Hi, good point! I will make the changes.

**Comment by tserg** [comment]
Hi @smonicas, any update on the next steps? We are pending this to integrate Caracal into our CI.

**Comment by smonicas** [comment]
Hi, sorry i didn't imagine that you were using an unreleased scarb version but we'll do a release next week

**Pull request merged**
